version: '3'

services:
  client:
    build: ./client
    ports: 
      - 3000:3000
    volumes: 
      - ./client/package*.json:app/
      - ./client:app/
  flask:
    build: ./server
    ports:
      - 5000:5000
    expose: 
      - 5000
    volumes: 
      - ./server:app/
    command: gunicorn -b 0.0.0.0:5000 app:app --daemon
  nginx:
    build: .
    ports: 
      - 8080:8080
    expose: 
      - 8080
    depends_on: 
      - client
      - flask
    volumes: 
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
    
    